### ISSUE TITLE
Resize

### ISSUE THREAD

**Issue by hakao32** [anjalp/Minimalistic-Flat-Modern-GUI-Template#1]
How can I resize the page? I tried it over qt designer but when I run the code it becomes default.

**Comment by anjalp** [comment]
Yeh man, since we have used the _QtCore.Qt.FramelessWindowHint_ and _QtCore.Qt.WA_TranslucentBackground_, in the Main Window app frame is set to frameless as so we cannot resize the window by dragging any side of the window. 
But in the python file: **_ui_function.py_**,  at line 154 we can see 3 lines of commended code:

154        #-----> RESIZE USING DRAG                                       THIS CODE TO DRAG AND RESIZE IS IN PROTOPYPE.
155        #self.sizegrip = QSizeGrip(self.ui.frame_drag)
156        #self.sizegrip.setStyleSheet("width: 20px; height: 20px; margin 0px; padding: 0px;")

Uncommend the 155 and 156 line, thereby you can resize the window by click and drag of the right bottom corner of the window

154        #-----> RESIZE USING DRAG                                       THIS CODE TO DRAG AND RESIZE IS IN PROTOPYPE.
_155        self.sizegrip = QSizeGrip(self.ui.frame_drag)
156        self.sizegrip.setStyleSheet("width: 20px; height: 20px; margin 0px; padding: 0px;")_

I didn't enabled this feature as default, but you can just do so by uncommend the lines as above described. I have uploaded a video in the **issue** folder of the _Minimalistic-Flat-Modern-GUI-Template_, chk the video named : _**resize.mp4**_
